### ISSUE TITLE
Nullpointer on scanning branches and create webhooks or receive webhook calls

### ISSUE THREAD

**Issue by MCMicS** [jenkinsci/gitlab-branch-source-plugin#292] opened 2023-03-28 08:53 UTC
I updated to version 647 and secret was migrated but no webhook is received because missing secretkey. If i rescan my Jobs it results in Nullpointer.
I also tried zo save my Gitlab server settings again and choose the empty entry in popup. But the result is the same.
I downgraded to 645 and it works again

Reference to PR: #283

**Comment by MCMicS** [comment] 2023-04-06 07:44
This happens also if set secret to 'empty'
![grafik](https://user-images.githubusercontent.com/4604206/230308844-0c1f7f72-9422-4075-be43-7cca964c0176.png)

```
Caught unhandled exception with ID 59912039-463a-4a14-a5b1-20c5d351411b
java.lang.Exception: Expecting a valid secret token
	at org.kohsuke.stapler.HttpResponses.error(HttpResponses.java:92)
	at io.jenkins.plugins.gitlabbranchsource.GitLabWebHookAction.doPost(GitLabWebHookAction.java:75)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:207)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:558)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:475)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:698)
```

**Comment by rfrebyLF** [comment] 2023-04-26 16:00
Same for us. The only way to fix that after loading our configuration as code is to manually go on settings, and set the secretToken to a copy of the  credential access token.

**Comment by jmini** [comment] 2023-05-30 11:30
I think this issue is a duplicate of #304

**Closed** 2023-06-02 14:25 UTC
